### ISSUE TITLE
Tests failing on import of datalab functionality

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#117]
When I try to run unit tests, for example:

    python -m unittest explainaboard/tests/test_text_classification.py

I get the following error:

    Error
    Traceback (most recent call last):
      File "/Users/gneubig/opt/anaconda3/envs/exp/lib/python3.8/unittest/loader.py", line 34, in testFailure
        raise self._exception
    ImportError: Failed to import test module: test_text_classification
    Traceback (most recent call last):
      File "/Users/gneubig/opt/anaconda3/envs/exp/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
        module = __import__(module_name)
      File "/Users/gneubig/work/ExplainaBoard/explainaboard/tests/test_text_classification.py", line 4, in <module>
        from explainaboard import FileType, Source, TaskType, get_loader, get_processor
      File "/Users/gneubig/work/ExplainaBoard/explainaboard/__init__.py", line 4, in <module>
        from .processors import get_processor
      File "/Users/gneubig/work/ExplainaBoard/explainaboard/processors/__init__.py", line 5, in <module>
        from . import extractive_qa
      File "/Users/gneubig/work/ExplainaBoard/explainaboard/processors/extractive_qa.py", line 6, in <module>
        from explainaboard.builders.extractive_qa import QAExtractiveExplainaboardBuilder
      File "/Users/gneubig/work/ExplainaBoard/explainaboard/builders/extractive_qa.py", line 14, in <module>
        from datalabs.operations.aggregate.qa_extractive import qa_extractive_aggregating
    ModuleNotFoundError: No module named 'datalabs.operations.aggregate.qa_extractive'

The immediate fix to this is probably to bump DataLab's version?

More generally, I'm a bit wary of having such a tight and complicated coupling between ExplainaBoard and DataLab, as it seems that it may require someone who contributes to ExplainaBoard to be intimately familiar with DataLab as well, which is a lot to expect given the complexity of the DataLab project. We can discuss the best way to handle this going forward I guess.

**Comment by pfliu-nlp** [comment]
I actually can run it successfully by following commands:

```python
conda create --name explainaboard_test python=3
conda activate explainaboard_test
git clone https://github.com/neulab/ExplainaBoard.git
cd ExplainaBoard/
pip install .[dev]

python -m unittest explainaboard/tests/test_text_classification.py

```

**Comment by lyuyangh** [comment]
This is also failing for me. It's failing because explainaboard doesn't specify a version number for datalabs. pip won't automatically upgrade to the latest version because of that. I guess since we have a circular dependency, we cannot specify a specific version for datalabs? Or maybe for now, we can specify the datalabs version in explainaboard repo but leave the explainaboard version unspecified in the datalabs repo. Would that work?

**Comment by pfliu-nlp** [comment]
>"Or maybe for now, we can specify the datalabs version in explainaboard repo but leave the explainaboard version unspecified in the datalabs repo. Would that work?"
Interesting, I think I have experienced "specify version number" -> "remove it" -> "specify it" now 
![image](https://user-images.githubusercontent.com/59123869/157773187-d572ed94-6254-4bc9-8869-007b030605c2.png)

>"Or maybe for now, we can specify the datalabs version in explainaboard repo but leave the explainaboard version unspecified in the datalabs repo. Would that work?"
I think this is a question for Graham since I'm fine with both.
( I'm trying to figure out how to install the latest version automatically previously, but didn't find an elegent way. Let me know if you have some idea)

**Comment by lyuyangh** [comment]
Oh, that makes sense. My environment had `datalabs == 0.2.7` but `datalabs.operations.aggregate.qa_extractive` was introduced until later. That's why I had to upgrade datalabs to the latest version. I think we just to specify a lower bound (>= xxx) for datalabs. but we probably don't need a specific version if datalabs is relatively stable.

**Comment by pfliu-nlp** [comment]
One thing I'm curious about is: when perfoming following commands:
```
conda create --name explainaboard_test python=3
conda activate explainaboard_test
```
shouldn't we install everything from scratch, so the default version of datalabs should be the latest one?

**Comment by lyuyangh** [comment]
> One thing I'm curious about is: when perfoming following commands:
> 
> ```
> conda create --name explainaboard_test python=3
> conda activate explainaboard_test
> ```
> 
> shouldn't we install everything from scratch, so the default version of datalabs should be the latest one?

Yeah, I think you are right. This wouldn't be an issue if someone installs everything in a clean environment. I was resuing an environment with a lower version.

**Comment by neubig** [comment]
I think the best solution here is to specify a `>=` dependency instead of an `==` dependency. Shouldn't that solve the problem?

**Comment by pfliu-nlp** [comment]
We can go with it.
