### ISSUE TITLE
Inconsistent formats of `bucket_samples` in different tasks

### ISSUE THREAD

**Issue by pfliu-nlp** [neulab/ExplainaBoard#283]
Currently, the formats (schemas) of `bucket_samples` in different tasks are inconsistent, which poses the challenges for frontend visualization and results in  the error `B4` in https://github.com/neulab/explainaboard_web/issues/127

Note:
It's not difficult to unify the following formats in SDK but we may also want to reflect something mentioned in this issue: https://github.com/neulab/ExplainaBoard/issues/272

##### Task
* classification
* kg_link_tail_prediction
* aspect_based_sentiment_classification
* text_pair_classification
* qa_multiple_choice
* conditional-text-generation [sample-level features]

##### Sample code
```python
                if sys_info.is_print_case:
                    if true_label != predicted_label:
                        bucket_case = str(s_id)
                        bucket_cases.append(bucket_case)

            bucket_performance = BucketPerformance(
                bucket_name=bucket_interval,
                n_samples=len(sample_ids),
                bucket_samples=bucket_cases,
            )
```

##### Task
* named_entity_recognition
* word_segmentation

##### Sample Code
```python
            system_output_id = sys_output[span[0]]["id"]
            error_case = {
                "text": str(system_output_id),
                "span": span[2],
                "true_label": true_label,
                "predicted_label": pred_label,
            }
            case_list.append(error_case)
```

##### Task
* conditional-text-generation [span-level features]
* summarization [span-level features]
* machine-translation [span-level features]

##### Sample Code

```python
            for sid, tid in toks_true:
                      ....

            bucket_performance = BucketPerformance(
                bucket_name=bucket_interval,
                n_samples=len(toks_true),
                bucket_samples=toks_true,
                performances=[performance],
            )



```

**Comment by neubig** [comment]
I agree, and we can also perhaps think of this together with this issue: https://github.com/neulab/ExplainaBoard/issues/272

**Comment by pfliu-nlp** [comment]
> 

Aha, yes, I actually mentioned 272 at the beginning of this page.

**Comment by neubig** [comment]
Woops sorry! I missed that paragraph

**Comment by OscarWang114** [comment]
@pfliu-nlp About the `table_schema.py` you mentioned earlier, it seems to be deleted from the repo but can be recovered from this [commit](https://github.com/neulab/ExplainaBoard/pull/157/commits/91a027b5278d09352087f826fa817e965867c594). 

This isn't the actual commit that deleted it but the one that Graham deleted and then restored it. I think the file content should be the same though!

**Comment by OscarWang114** [comment]
I discussed this briefly with @lyuyangh , and here are some of our thoughts:

## 1. Frontend becoming task-dependent is inevitable (but in a good way)

Different NLP tasks have their own ideal ways of presenting analysis results and examples. For instance, BRAT works well for NER examples, while common token highlighting or visualizing the embedding space might work well for text-generative examples. This makes it inevitable for the frontend to be task-dependent, and I think it's totally fine and makes great sense.

## 2. What info should the SDK provide to the web interface?

Previously we've discussed whether `table_schema.py` should reside in SDK or the web repo. 
Reason for keeping in SDK:
* When adding new tasks, developers can provide the expected format/UI-related info in the same repo.

Reason keeping in frontend
* This file is only used by frontend, so it makes sense to move it there.
* Providing UI-related info is not SDK's responsibility.

With task-dependent becoming inevitable (1.), We think it makes more sense to have UI-related info residing in the web repo. The SDK should only provide information about the data and schema (e.g., data classes). 

However, since the frontend uses TypeScript (meaning all field types must be precisely defined for the code to work), we'll need to manually convert the Python data classes in SDK into TypeScript interfaces, which shouldn't be a big problem since there are only a few types of bucket samples.

## 3. Schema

For the bucket samples, we think it'd be nice to use data classes. We can have three types of classes corresponding to the three formats above (and perhaps inheriting from the same base class?). These classes can be directly used by the web backend.

## Some other suggestions from Lyuyang regarding the frontend:
Create something like an API wrapper that handles the format of bucket samples as early as possible, using the task type information. The task type info is then no longer needed for any subsequent processing/rendering. The API wrapper acts like a task handler and can return the essential column information and format for the "example table class".

**Comment by neubig** [comment]
This is fixed.
