### ISSUE TITLE
`FeatureType.from_dict()` should ignore unused keys

### ISSUE THREAD

**Issue by lyuyangh** [neulab/ExplainaBoard#292]
`FeatureType.from_dict()` throws an exception if an extra key is provided. I think it should be safe to only extract keys that is defined for the dataclass.

Error message:
```
  File "/Users/lyuyangh/Developer/explainaboard_web/backend/src/impl/default_controllers_impl.py", line 268, in systems_analyses_post
    feature = FeatureType.from_dict(feature)  # dict -> Feature
  File "/opt/homebrew/Caskroom/miniforge/base/envs/eb-web/lib/python3.9/site-packages/explainaboard/feature.py", line 89, in from_dict
    return _fromdict_inner(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/eb-web/lib/python3.9/site-packages/explainaboard/feature.py", line 55, in _fromdict_inner
    return FEATURETYPE_REGISTRY[obj["_type"]](**result)
TypeError: __init__() got an unexpected keyword argument 'is_pre_computed'
```

**Comment by pfliu-nlp** [comment]
>"TypeError: __init__() got an unexpected keyword argument 'is_pre_computed'"

This PR mentioned this error.

`is_pre_computed` has already been removed from the refactored feature class, here I guess  having such an error is a good
thing (reminder)?

**Comment by neubig** [comment]
The issue here is that the new implementation is not backward compatible with features that were saved to the web UI database previously. (I actually also encountered this error)

Unfortunately we're probably now going to have to think a bit more about backward compatibility of serialization/deserialization like this, and there's a couple options:
1. Make sure the code is backward-compatible in general
2. Do versioning of the serialization/deserialization code
3. When we change the file format, re-run the analyses over affected database entries and re-populate the database

I tend to prefer a combination of (1) and (3), where what Lyuyang is recommending here is part of (1).

**Comment by lyuyangh** [comment]
I tried migrating the DB schema (removed all `is_pre_computed`) but I think there are several other things that need to be updated (e.g. some of the `_type` stored in the DB is no longer valid). I removed all the systems in the dev env. If we want to keep those system outputs in prod, I think we'll probably need to do 3?

**Comment by neubig** [comment]
Handled by https://github.com/neulab/explainaboard_web/pull/169
