### ISSUE TITLE
How to name metrics when registering them

### ISSUE THREAD

**Issue by pfliu-nlp** [neulab/ExplainaBoard#455]
There are two ways to name metrics

(1) 
```python

@dataclass
@metric_config_registry.register("AccuracyConfig")
class AccuracyConfig(MetricConfig):
    def to_metric(self):
        return Accuracy(self)

```

(2) 
```python
@dataclass
@metric_config_registry.register("Accuracy")
class AccuracyConfig(MetricConfig):
    def to_metric(self):
        return Accuracy(self)

```

Currently, we are using (1), which, however, is inconsistent with how the Processor names them. For example:

https://github.com/neulab/ExplainaBoard/blob/cd54c1b61e490295db8c1cfee8460aff4cce1880/explainaboard/processors/text_classification.py#L132

Which one do you prefer?

If we go with (2), this code should be modified to avoid naming bug:
https://github.com/neulab/ExplainaBoard/blob/cd54c1b61e490295db8c1cfee8460aff4cce1880/explainaboard/metrics/registry.py#L11

```python
config_cls = metric_config_registry.get_type(dikt["name"]) # instead of type
```

I could send a PR of this.

**Comment by odashi** [comment]
(1) and (2) were historically used at the same time, and (2) is removed by #400 to avoid ambiguity. I think which option (or even other naming convention) is okay so long as it has no ambiguity.

**Comment by pfliu-nlp** [comment]
thanks @odashi 
The truth is when I used

```python
@dataclass
@metric_config_registry.register("Accuracy")
class AccuracyConfig(MetricConfig):
    def to_metric(self):
        return Accuracy(self)

```

there will be an error, since the following function `metric_config_from_dict` will pass `AccuracyConfig` to 
https://github.com/neulab/ExplainaBoard/blob/cd54c1b61e490295db8c1cfee8460aff4cce1880/explainaboard/metrics/registry.py#L11

`metric_config_registry.get_type`, and `AccuracyConfig` hasn't been registered.



https://github.com/neulab/ExplainaBoard/blob/cd54c1b61e490295db8c1cfee8460aff4cce1880/explainaboard/serialization/registry.py#L93

Is the above behavior as expected:?

**Comment by odashi** [comment]
@pfliu-nlp Almost expected. If we registered the class as `Accuracy`, all config files need to follow the name `Accuracy`, and `AccuracyConfig` shouldn't work.

**Comment by odashi** [comment]
The `name` parameter of `MetricConfig` is independent from the registered class name; it is sometimes used to give a unique name for each metric with the same class (e.g., "Hits1", "Hits2", ...). If we gave `name="Accuracy"`, the class name in the registry is still `"AccuracyConfig"`.

**Comment by odashi** [comment]
@pfliu-nlp This is expected because all JSON in this repository contains `XConfig` rather than `X`. We don't synthesize the registered namy by code (as long as I understand). Current implementation you mentioned does only copying the registered name from dict, which is basically loaded from JSON.

There is another issue to reconsider registered names #446 , so it seems this topic needs to be discussed too in #446

**Comment by odashi** [comment]
@pfliu-nlp 

> AccuracyConfig -> Accuracy, since this will make metric names consistent with how we name them in Processor.

This is because the registry hosts MetricConfig, not Metric.

**Comment by neubig** [comment]
Thanks for the discussion! Regarding this:

> Currently, I want to modify all registered names of metrics from XConfig to X, for example, AccuracyConfig -> Accuracy, since this will make metric names consistent with how we name them in Processor.

Actually, this naming convention for metric names is just a general trend (because it makes sense), not a rule. For example, here is a counter-example, where we have different names for `Hits` metrics with different parameters: https://github.com/neulab/ExplainaBoard/blob/main/explainaboard/processors/kg_link_tail_prediction.py#L120

Because of this, I'd prefer to name the registered names of the metric configs to `XConfig` not just `X`, because it also matches with the class name and seems simplest. If there's a strong argument for `X` we could reconsider though.

**Comment by pfliu-nlp** [comment]
thanks! Conclusion: `name the registered names of the metric configs to XConfig not just X`
closed this issue based on this PR: https://github.com/neulab/ExplainaBoard/pull/454
