### ISSUE TITLE
Change to `~=` requirements

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#472]
Per the discussion here, we should be more rigorous in specifying the version numbers of the libraries that we depend on:
https://github.com/neulab/ExplainaBoard/pull/403#issuecomment-1242754774

**Comment by tetsuok** [comment]
I've created a pull request #560 to use `~=` operator, but it turned out this is not so straightforward. Transitive dependencies introduced by DataLab cause the CI jobs to fail when they run `pip install .`. We could revisit this issue once either the transitive dependencies or dependency on DataLab itself can be resolved.
