### ISSUE TITLE
Method for analysis of new extractive QA datasets is not clear

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#85]
Looking at the [documentation for Extractive QA](https://github.com/neulab/ExplainaBoard/blob/main/docs/task_extractive_qa.md) the file format is not clear with respect to how to analyze a *new* dataset. The system output JSON file specifies question IDs, but what if the dataset is not SQuAD but something entirely different, such as a dataset newly created by the user? How are the datasets specified, where do I get the question IDs?

It'd be nice if the documentation could be updated and/or support could be added for analyzing new datasets!

**Comment by pfliu-nlp** [comment]
After a second thought, I think adding qa task dataset-by-dataset would be a better way now (then we can merge them when seeing more cases) since we
* don't have more system outputs on other datasets, don't know what the common evaluation process (does the system output file cover all information of test set) is, therefore it's hard to generalize current qa evaluation processor.
* different datasets usually have different formats. For example, maybe other extractive qa datasets even don't have question id information.

I changed `extractive-qa` to `extractive-qa-squad`.

**Comment by neubig** [comment]
I think this is done.
